version: '3.8'

services:
  spark-master:
    image: bitnamilegacy/spark:3.5.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080" # Cluster UI
      - "7077:7077" # Communication Port
      - "4040:4040" # Job UI (DAG)
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./apps:/opt/bitnami/spark/apps

  spark-worker-1:
    image: bitnamilegacy/spark:3.5.2
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/bitnami/spark/data

  spark-worker-2:
    image: bitnamilegacy/spark:3.5.2
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/bitnami/spark/data